# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
import inspect

In [2]:
def ins(x):
    print(inspect.getsource(x))

In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

In [4]:
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)

1.22.3


In [6]:
answer(2)

print(np.__version__)
np.show_config()


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
answer(3)

Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
hint(4)

hint: size, itemsize


In [10]:
a = np.random.randint(0,1e17,10)

In [11]:
a.size

10

In [12]:
a.itemsize

8

In [13]:
a.size * a.itemsize

80

In [40]:
answer(4)

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [46]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [47]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
a = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
a = np.arange(10,20)
a = a[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

In [20]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
a = np.random.random((3,3,3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [78]:
a = np.random.rand(10,10)
print(a.min(), a.max())

0.010631931161773966 0.9805293225347


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [83]:
a = np.random.random(30)
print(a.mean())

0.5207548944453643


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [91]:
a = np.zeros((10,10))
a = np.pad(a, 1, constant_values=1)

In [92]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [96]:
a = np.ones((10,10))
a = np.pad(a, 1, constant_values=0)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

```

In [101]:
print(np.nan, False, False, np.nan, True, False)

nan False False nan True False


In [106]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [107]:
np.diag([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
a = np.zeros((8,8))

In [24]:
a[::2,1::2] = 1
a[1::2,::2] = 1

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [26]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
np.tile([[1,0],[0,1]], (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [39]:
a = np.random.rand(5,5)

In [41]:
z = (a - a.mean())/a.std()

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [55]:
np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [56]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
a @ b

array([[0.44335344, 0.56806418],
       [0.84127523, 0.97961224],
       [0.77970648, 1.06791211],
       [0.67739451, 1.12028856],
       [0.7985082 , 0.92189634]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [79]:
a = np.random.randint(0, high=10,size=20)
print(a)

[5 1 5 6 5 3 5 8 0 0 2 1 5 6 2 6 7 1 0 4]


Notice here that we use logical and & and parenthesis. Using `a > 3 and a < 8` doesn't work. 

In [89]:
a[(a > 3) & (a < 8)] *= -1

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
sum(range(5), -1)

9

In [8]:
np.sum(range(5), -1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [11]:
a = np.ones(4, int)
a

array([1, 1, 1, 1])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/tm/kwxmcdkj60gck7rdnxqb9s980000gn/T/ipykernel_27665/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/tm/kwxmcdkj60gck7rdnxqb9s980000gn/T/ipykernel_27665/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
np.ceil(np.random.rand(3) - 1)

array([-0., -0., -0.])

In [35]:
a = np.random.normal(size=(4))
a

array([-0.54787997,  2.58137949, -0.12574281,  1.33805964])

In [36]:
np.where(a > 0, np.ceil(a), np.floor(a))

array([-1.,  3., -1.,  2.])

In [37]:
np.ceil(a)

array([-0.,  3., -0.,  2.])

In [29]:
hint(29)

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where


In [30]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [40]:
a, b = np.random.randint(0,high=5, size=(2,10))

In [44]:
print(a,b)

[3 1 2 4 0 4 2 2 1 4] [4 4 4 1 1 1 3 0 1 0]


In [48]:
np.intersect1d(a,b)

array([0, 1, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [52]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [58]:
np.sqrt(-1)

/var/folders/tm/kwxmcdkj60gck7rdnxqb9s980000gn/T/ipykernel_27665/3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [59]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [66]:
date = np.datetime64

In [76]:
now = date('today')

In [77]:
np.timedelta64(1, 'D') + now

numpy.datetime64('2022-04-25')

In [78]:
np.timedelta64(-1, 'D') + now

numpy.datetime64('2022-04-23')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [5]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [6]:
a,b = np.random.rand(2,10)

In [10]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [12]:
a = np.random.rand(10)*100
a

array([54.05618722,  9.83975794, 73.9952611 , 47.9855533 , 81.0504229 ,
       16.20177244, 21.182171  , 65.15484212, 57.38023751, 88.64287612])

In [13]:
np.floor(a)

array([54.,  9., 73., 47., 81., 16., 21., 65., 57., 88.])

In [17]:
np.int_(a)

array([54,  9, 73, 47, 81, 16, 21, 65, 57, 88])

In [22]:
np.trunc(a)

array([54.,  9., 73., 47., 81., 16., 21., 65., 57., 88.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
np.tile(np.arange(0,5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [37]:
np.zeros((5,5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
np.fromiter(range(10), int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [48]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [54]:
a = np.random.rand(10)
a.sort()
a

array([0.11564159, 0.22511233, 0.2919019 , 0.30655047, 0.44605045,
       0.57620705, 0.58429837, 0.6274834 , 0.66481405, 0.94653188])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [57]:
a = np.random.rand(1000)

In [58]:
%timeit np.add.reduce(a)

2.67 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [60]:
%timeit sum(a)

89.2 µs ± 877 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [61]:
%timeit np.sum(a)

5.95 µs ± 70.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [62]:
a,b = np.random.rand(2,10)

In [66]:
np.allclose(a,b)

False

In [69]:
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [71]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [77]:
a = np.random.normal(size=(10,2))

In [90]:
r = np.sqrt((a**2).sum(1))

In [91]:
phi = np.arctan2(a[:,1], a[:,0])

In [92]:
polar = np.vstack([r,phi]).T

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [101]:
a = np.random.rand(10)

In [103]:
a[a.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [104]:
x = np.linspace(0,1,10)
y = np.linspace(0,1,10)

In [116]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [136]:
x,y = np.random.random(size=(2,5))

In [143]:
1. / np.subtract.outer(x,y)

array([[  9.42794638,  -1.16736706,  -2.17974527,  -5.54805101,
        -47.79070996],
       [  1.96161592,  -2.2079323 , -18.16429823,   4.47481998,
          2.61238763],
       [ 10.2365458 ,  -1.15605998,  -2.14065088,  -5.30161101,
        -34.12619466],
       [  1.47708927,  -3.50030884,   8.91501495,   2.55953454,
          1.81813242],
       [  9.16460101,  -1.17153535,  -2.19432339,  -5.64348048,
        -55.93870867]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [147]:
np.iinfo(int)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [149]:
np.finfo(float)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [154]:
answer(48)

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆)

In [158]:
arr = np.add.outer(x,y)

In [ ]:
answer(49)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [169]:
x[np.abs(x - 0.5).argmin()]

0.5213510273158312

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [7]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])

/var/folders/tm/kwxmcdkj60gck7rdnxqb9s980000gn/T/ipykernel_32521/736261935.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [12]:
Z[0]['position']['x']

0.0

In [14]:
dt = np.dtype([('pos', [('x',float),('y',float)]),
          ('ang', [('phi', float), ('pi', float)])])

In [19]:
np.zeros(5, dt)[0]['ang']['phi']

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [20]:
x = np.random.rand(100,2)

In [ ]:
np.subtract.outer()

In [29]:
np.sqrt(np.subtract.outer(x[:,0], x[:,0])**2 + np.subtract.outer(x[:,1], x[:,1])**2)

array([[0.        , 0.55021917, 0.48918032, ..., 0.23593508, 0.43840568,
        0.89431145],
       [0.55021917, 0.        , 0.1450748 , ..., 0.31569367, 0.12396679,
        0.41608358],
       [0.48918032, 0.1450748 , 0.        , ..., 0.25985512, 0.08425487,
        0.55836289],
       ...,
       [0.23593508, 0.31569367, 0.25985512, ..., 0.        , 0.20264739,
        0.6853875 ],
       [0.43840568, 0.12396679, 0.08425487, ..., 0.20264739, 0.        ,
        0.53283635],
       [0.89431145, 0.41608358, 0.55836289, ..., 0.6853875 , 0.53283635,
        0.        ]])

In [34]:
import scipy.spatial

In [36]:
scipy.spatial.distance.cdist(x,x)

array([[0.        , 0.55021917, 0.48918032, ..., 0.23593508, 0.43840568,
        0.89431145],
       [0.55021917, 0.        , 0.1450748 , ..., 0.31569367, 0.12396679,
        0.41608358],
       [0.48918032, 0.1450748 , 0.        , ..., 0.25985512, 0.08425487,
        0.55836289],
       ...,
       [0.23593508, 0.31569367, 0.25985512, ..., 0.        , 0.20264739,
        0.6853875 ],
       [0.43840568, 0.12396679, 0.08425487, ..., 0.20264739, 0.        ,
        0.53283635],
       [0.89431145, 0.41608358, 0.55836289, ..., 0.6853875 , 0.53283635,
        0.        ]])

In [38]:
X,Y = np.atleast_2d(x[:,0], x[:,1])

In [45]:
np.sqrt((X-X.T)**2 + (Y-Y.T)**2)

array([[0.        , 0.55021917, 0.48918032, ..., 0.23593508, 0.43840568,
        0.89431145],
       [0.55021917, 0.        , 0.1450748 , ..., 0.31569367, 0.12396679,
        0.41608358],
       [0.48918032, 0.1450748 , 0.        , ..., 0.25985512, 0.08425487,
        0.55836289],
       ...,
       [0.23593508, 0.31569367, 0.25985512, ..., 0.        , 0.20264739,
        0.6853875 ],
       [0.43840568, 0.12396679, 0.08425487, ..., 0.20264739, 0.        ,
        0.53283635],
       [0.89431145, 0.41608358, 0.55836289, ..., 0.6853875 , 0.53283635,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [63]:
a = np.random.rand(5).astype(float)

In [65]:
a[:] = a.view(int)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [76]:
from io import StringIO

In [77]:
s = StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")

In [79]:
np.genfromtxt(s,delimiter=',',filling_values=0)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  0.,  0.,  7.,  8.],
       [ 0.,  0.,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [84]:
list(np.ndenumerate(np.random.rand(3,4)))

[((0, 0), 0.39345299652773424),
 ((0, 1), 0.2371618947520283),
 ((0, 2), 0.5430579711132265),
 ((0, 3), 0.23131664878957847),
 ((1, 0), 0.6762197746684627),
 ((1, 1), 0.6249394740463343),
 ((1, 2), 0.13909821134627742),
 ((1, 3), 0.7957101920416567),
 ((2, 0), 0.7898760644554543),
 ((2, 1), 0.33884265971612393),
 ((2, 2), 0.299180748080229),
 ((2, 3), 0.9013526254751838)]

In [85]:
list(np.ndindex((3,4)))

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3)]

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [88]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [95]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [97]:
a = np.random.rand(3,6)
a

array([[0.12546648, 0.83047286, 0.32833565, 0.52255127, 0.28457844,
        0.59061837],
       [0.67939225, 0.50155972, 0.0940234 , 0.29125058, 0.94558234,
        0.13591829],
       [0.21557079, 0.97304483, 0.16608224, 0.26347346, 0.33521965,
        0.59019094]])

In [107]:
a - a.mean(1).reshape(-1,1)

array([[-0.32153736,  0.38346901, -0.1186682 ,  0.07554743, -0.16242541,
         0.14361452],
       [ 0.23810449,  0.06027195, -0.34726436, -0.15003718,  0.50429458,
        -0.30536947],
       [-0.20835953,  0.54911451, -0.25784808, -0.16045686, -0.08871066,
         0.16626062]])

In [108]:
a - a.mean(1,keepdims=True)

array([[-0.32153736,  0.38346901, -0.1186682 ,  0.07554743, -0.16242541,
         0.14361452],
       [ 0.23810449,  0.06027195, -0.34726436, -0.15003718,  0.50429458,
        -0.30536947],
       [-0.20835953,  0.54911451, -0.25784808, -0.16045686, -0.08871066,
         0.16626062]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [126]:
a = np.random.rand(5,1)

In [127]:
a.flat[np.abs(a - 0.1).argmin()]

0.22546288392175862

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [131]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


In [140]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])

In [141]:
for x,y,z in it: z[...] = x + y

In [144]:
it.operands

(array([[0],
        [1],
        [2]]),
 array([[0, 1, 2]]),
 array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]))

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [163]:
a = np.random.rand(2,2,2,2)

In [164]:
shape = a.shape

In [165]:
a.reshape(shape[:-2]+(-1,)).sum(-1)

array([[1.89460544, 1.82054509],
       [3.05721426, 2.06585426]])

In [166]:
a.sum((-1,-2))

array([[1.89460544, 1.82054509],
       [3.05721426, 2.06585426]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [169]:
hint(69)

hint: np.diag


In [174]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [177]:
np.dot(A,B)

array([[1.56647386, 2.11351962, 1.75067106, 1.09301221, 1.47541034],
       [1.47557845, 1.79536096, 1.68667784, 0.85059787, 1.0590352 ],
       [1.25730985, 1.39070561, 1.07350698, 0.55668448, 1.09871692],
       [1.67326358, 1.65443374, 1.58918659, 0.78254433, 1.15005076],
       [1.00642705, 1.25451357, 0.86308741, 0.3060262 , 0.86352134]])

In [181]:
np.diag(A @ B)

array([1.56647386, 1.79536096, 1.07350698, 0.78254433, 0.86352134])

In [186]:
np.einsum('ij, ji -> i',A,B)  # diagonal

array([1.56647386, 1.79536096, 1.07350698, 0.78254433, 0.86352134])

In [187]:
np.einsum('ij, ji',A,B)  # Trace of result

6.081407474212273

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)